### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by forliuyifei** [miguelmalvarez/downloadTwitterPictures#9]
```
python run.py --username NatGeoPhotos --num 10
Traceback (most recent call last):
  File "/storage/emulated/0/ADM/downloadTwitterPictures/run.py", line 1, in <module>
    import tweepy
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/tweepy/__init__.py", line 17, in <module>
    from tweepy.streaming import Stream, StreamListener
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/tweepy/streaming.py", line 358
    def _start(self, async):
                     ^
SyntaxError: invalid syntax
```

**Comment by 2thecurve** [comment]
Same error as user.

**Comment by miguelmalvarez** [comment]
Can you please share how you run the script?

**Comment by forliuyifei** [comment]
> Can you please share how you run the script?

python run.py --username NatGeoPhotos --num 10

**Comment by miguelmalvarez** [comment]
Sorry, I should have seen that from your original comment. I cannot replicate your error with the current codebase and using python 3.9 (which is the one I think you are using). Can you please confirm what versions of wget and tweepy are you using? I have changed the requirements.txt a couple of days ago and you should use the following:

wget==3.2
tweepy==3.8.0

There was a bug that I fixed today that made the system crash due to some outdated format for the pictures urls. I am not sure if this was related to your problem but please pull the latest changes.

**Comment by forliuyifei** [comment]
> Sorry, I should have seen that from your original comment. I cannot replicate your error with the current codebase and using python 3.9 (which is the one I think you are using). Can you please confirm what versions of wget and tweepy are you using? I have changed the requirements.txt a couple of days ago and you should use the following:
> 
> wget==3.2
> tweepy==3.8.0
> 
> There was a bug that I fixed today that made the system crash due to some outdated format for the pictures urls. I am not sure if this was related to your problem but please pull the latest changes.

Well, I seem to know the problem, because Termux running on my phone cannot install tweepy,And the version of wget is 1.21.1
